[package]
org = "sashm"
name = "social_media_service"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

# [database]
# mysql = {
#     driver_path = "./external-libs/mysql-connector-j-8.3.0.jar"
# }
